# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3916d869c6390f8ae43bd89eaa8a6659702bc0784a5455445a3ba872f4b366f6ccda1ea8f757320a71a0136ac0d89d99531601e79aff7847ad4dd77ea8884d07

test:
  secret_key_base: 0bea82a957af211a6b9e3460840d81a70c8c0b8d219ea009f4217fe9554f1539f2dab76dae227ff19aef2a5a02dde75af1479a885b361494788ccd244b954058

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
